name: Deploy to GCP

env:
  STAGING_SERVICE_NAME: staging-example
  PRODUCTION_SERVICE_NAME: production-example
  PROJECT_ID: training-projects-430617
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/training-projects-430617/cicd-example/cicd-example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_EXAMPLE }}' 
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image 
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to staging
        run: |
          gcloud run deploy $STAGING_SERVICE_NAME \
          --image ${{ env.DOCKER_IMAGE_URL }}:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

      - name: Run integration tests
        run: python tests/integration.py

      - name: Deploy to production
        run: |
          gcloud run deploy $PRODUCTION_SERVICE_NAME \
          --image ${{ env.DOCKER_IMAGE_URL }}:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated