name: Deploy to GCP

env:
  SERVICE_NAME: cicd-example
  PROJECT_ID: training-projects-430617
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/training-projects-430617/cicd-example/cicd-example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_EXAMPLE }}' 
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image 
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME SERVICE _NAME
          gcloud run deploy $SERVICE_NAME \
          --image ${{ env.DOCKER_IMAGE_URL }}:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
      # - name: Install dependencies
      #   run: sudo pip3 install google-api-python-client oauth2client
      - name: Integration tests
        run: pytest